"""Deterministic analysis engine (docs/analysis-engine.md).

Pure, reproducible computation — no LLM involvement, ever. This package must
never import `delium.agents`.

Implemented: the profit engine (fees + profit + scenarios). Not yet: demand,
competition, differentiation, risk, and scoring.
"""

from delium.analysis.competition import analyze_competition
from delium.analysis.cross_market import (
    analyze_cross_market,
    analyze_cross_markets,
    assess_source,
    assess_target,
    assess_transferability,
    compute_market_gap,
    match_products,
)
from delium.analysis.demand import DemandError, analyze_demand, load_velocity_curves
from delium.analysis.differentiation import analyze_differentiation
from delium.analysis.fees import FeeError, compute_fees, load_fee_table
from delium.analysis.listing import compute_listing_quality
from delium.analysis.marketplaces import MARKETPLACES, get_marketplace
from delium.analysis.models import (
    Addressability,
    AsinHistory,
    BeatableSlots,
    BrandConcentration,
    BsrPoint,
    BsrTrend,
    BundleSignal,
    CompetitionConfidence,
    CompetitionConfig,
    CompetitionInput,
    CompetitionReport,
    CompetitorSnapshot,
    Confidence,
    ConfigSnapshot,
    CrossMarketComponent,
    CrossMarketConfidence,
    CrossMarketReport,
    CrossMarketVerdict,
    DemandConfig,
    DemandReport,
    DifferentiationConfidence,
    DifferentiationConfig,
    DifferentiationInput,
    DifferentiationReport,
    DifferentiationTheme,
    DiffReview,
    Dimensions,
    FeatureRequest,
    FeeBreakdown,
    FeeTable,
    GateResult,
    KeywordDatum,
    KeywordDemand,
    KillResult,
    LaunchAssumptions,
    ListingInput,
    ListingQualityAdvantage,
    ListingQualityReport,
    LocalizationFlag,
    MarketGap,
    Marketplace,
    MarketplaceInfo,
    MarketplaceProduct,
    MatchConfidence,
    PillarScore,
    PriceCompetition,
    PricePoint,
    ProductMatch,
    ProfitInputs,
    ProfitResult,
    RawTheme,
    ReviewMoat,
    ReviewVelocity,
    RiskConfidence,
    RiskConfig,
    RiskFlag,
    RiskInput,
    RiskReport,
    RiskRules,
    RiskSeverity,
    SalesEstimate,
    ScenarioAdjustment,
    ScenarioAssumptions,
    ScenarioSet,
    ScoreConfidence,
    ScoredOpportunity,
    ScoringInput,
    Seasonality,
    SourceMarketEvidence,
    SourceMarketInput,
    SourceMaturity,
    Subscore,
    TargetMarketEvidence,
    TargetMarketInput,
    TargetPresence,
    ThemeKind,
    Transferability,
    TransferabilityFactor,
    TransferabilityInput,
    TransferabilityLevel,
    VelocityCurves,
    Verdict,
)
from delium.analysis.profit import compute_profit, compute_scenarios, confidence_for
from delium.analysis.risk import RiskError, analyze_risk, load_risk_rules
from delium.analysis.scoring import score_opportunity

__all__ = [
    "Addressability",
    "AsinHistory",
    "BeatableSlots",
    "BrandConcentration",
    "BsrPoint",
    "BsrTrend",
    "BundleSignal",
    "CompetitionConfidence",
    "CompetitionConfig",
    "CompetitionInput",
    "CompetitionReport",
    "CompetitorSnapshot",
    "DiffReview",
    "DifferentiationConfidence",
    "DifferentiationConfig",
    "DifferentiationInput",
    "DifferentiationReport",
    "DifferentiationTheme",
    "FeatureRequest",
    "GateResult",
    "KillResult",
    "PillarScore",
    "RawTheme",
    "RiskConfidence",
    "RiskConfig",
    "RiskError",
    "RiskFlag",
    "RiskInput",
    "RiskReport",
    "RiskRules",
    "RiskSeverity",
    "ScoreConfidence",
    "ScoredOpportunity",
    "ScoringInput",
    "Verdict",
    "ConfigSnapshot",
    "ThemeKind",
    "analyze_differentiation",
    "analyze_risk",
    "load_risk_rules",
    "score_opportunity",
    "Confidence",
    "DemandConfig",
    "DemandError",
    "DemandReport",
    "Dimensions",
    "FeeBreakdown",
    "FeeError",
    "FeeTable",
    "KeywordDatum",
    "KeywordDemand",
    "LaunchAssumptions",
    "ListingInput",
    "ListingQualityAdvantage",
    "ListingQualityReport",
    "PriceCompetition",
    "PricePoint",
    "ProfitInputs",
    "ProfitResult",
    "ReviewMoat",
    "ReviewVelocity",
    "SalesEstimate",
    "ScenarioAdjustment",
    "ScenarioAssumptions",
    "ScenarioSet",
    "Seasonality",
    "Subscore",
    "VelocityCurves",
    "analyze_competition",
    "analyze_demand",
    "compute_fees",
    "compute_listing_quality",
    "compute_profit",
    "compute_scenarios",
    "confidence_for",
    "load_fee_table",
    "load_velocity_curves",
    # cross-market discovery
    "MARKETPLACES",
    "Marketplace",
    "MarketplaceInfo",
    "MarketplaceProduct",
    "MatchConfidence",
    "ProductMatch",
    "SourceMarketInput",
    "SourceMarketEvidence",
    "SourceMaturity",
    "TargetMarketInput",
    "TargetMarketEvidence",
    "TargetPresence",
    "MarketGap",
    "Transferability",
    "TransferabilityInput",
    "TransferabilityFactor",
    "TransferabilityLevel",
    "LocalizationFlag",
    "CrossMarketComponent",
    "CrossMarketConfidence",
    "CrossMarketReport",
    "CrossMarketVerdict",
    "get_marketplace",
    "match_products",
    "assess_source",
    "assess_target",
    "assess_transferability",
    "compute_market_gap",
    "analyze_cross_market",
    "analyze_cross_markets",
]
